apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-network-scan
spec:
  schedule: "0 2 * * *" # standard Cron syntax for 2:00 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true # Bypasses K8s network isolation
          dnsPolicy: ClusterFirstWithHostNet
          containers:
          - name: vuln-scanner
            image: vuln-scanner:v2
            imagePullPolicy: IfNotPresent # Tells K8s to use the local image, not download from the internet
            command: ["python", "scan_job.py"]
            envFrom:
            - configMapRef:
                name: scanner-config
          restartPolicy: OnFailure